export const state = {
  db: null,
  firebaseReady: false,
  selectedUserId: null,
  selectedUserLabel: "",
  currentUserData: null,
  currentGeneration: null,
  currentGenerationPokemonList: null,
  currentGenerationMasterPromise: null,
  currentGenerationMasterError: null,
  isLoadingUser: false,
  quizType: "math",
  selectedLevel: 1,
  currentQuestionIndex: 0,
  correctCount: 0,
  currentCorrectAnswer: 0,
  currentCorrectCountryId: "",
  isAnswered: false,
  quizTimerId: null,
  countryMasterList: null,
  countryMasterPromise: null,
  flagQuestions: [],
  currentFlagQuestion: null,
  pendingRewardPokemon: [],
  pendingRewardPokemonList: [],
  isSavingReward: false,
  lastProgressResult: null,
  generationStartLevel: 1,
  generationStartTarget: null,
  selectedZukanGeneration: null,
  generationMasterCache: {},
  generationMasterPromises: {}
};

window.AppState = state;
